AppConsumer/Controllers/SolicitudController.cs
using AppConsumer.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using WebAPI.Models;

namespace AppConsumer.Controllers
{
    public class SolicitudController : Controller
    {
        HttpClientHandler _clientHandler = new HttpClientHandler();

        List<Solicitud> _oSolicitudes = new List<Solicitud>();
           

        public SolicitudController()
        {
            _clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<List<Solicitud>> GetSolicitudes()
        {
            _oSolicitudes = new List<Solicitud>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:44334/api/Solicitud"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _oSolicitudes = JsonConvert.DeserializeObject<List<Solicitud>>(apiResponse);
                }
            }

            return _oSolicitudes;
        }

       

        [HttpGet]
        public async Task<List<Solicitud>> GetSolicitudByPeriodo(string periodo)
        {
            _oSolicitudes = new List<Solicitud>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:44334/api/Solicitud/periodo/" + periodo))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _oSolicitudes = JsonConvert.DeserializeObject<List<Solicitud>>(apiResponse);
                }
            }

            return _oSolicitudes;
        }


        [HttpGet]
        public async Task<List<Solicitud>> GetSolicitudByFecha(string fecha)
        {
            _oSolicitudes = new List<Solicitud>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:44334/api/Solicitud/fecha/" + fecha))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _oSolicitudes = JsonConvert.DeserializeObject<List<Solicitud>>(apiResponse);
                }
            }

            return _oSolicitudes;
        }

        [HttpGet]
        public async Task<List<Solicitud>> GetSolicitudByIdAlumno(int id)
        {
            _oSolicitudes = new List<Solicitud>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:44334/api/Solicitud/alumno/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _oSolicitudes = JsonConvert.DeserializeObject<List<Solicitud>>(apiResponse);
                }
            }

            return _oSolicitudes;
        }


        [HttpGet]
        public async Task<List<Solicitud>> GetSolicitudByAlumno(string nombres)
        {
            _oSolicitudes = new List<Solicitud>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:44334/api/Solicitud/alumno/nombre/" + nombres))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _oSolicitudes = JsonConvert.DeserializeObject<List<Solicitud>>(apiResponse);
                }
            }

            return _oSolicitudes;
        }

        [HttpGet]
        public async Task<List<Solicitud>> GetSolicitudByCurso(string curso)
        {
            _oSolicitudes = new List<Solicitud>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:44334/api/Solicitud/cursos/" + curso))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _oSolicitudes = JsonConvert.DeserializeObject<List<Solicitud>>(apiResponse);
                }
            }

            return _oSolicitudes;
        }

        


        public IActionResult Consulta()
        {
            return View();
        }

        [HttpGet]
        public async Task<List<Solicitud>> BuscarSolicitud(string nombre)
        {
            _oSolicitudes = new List<Solicitud>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:44334/api/Solicitud/" + nombre))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _oSolicitudes = JsonConvert.DeserializeObject<List<Solicitud>>(apiResponse);
                }
            }

            return _oSolicitudes;
        }

        [HttpPost]
        public async Task<Solicitud> InsertSolicitud(Solicitud solicitud)
        {
            solicitud.FechaSolicitud = DateTime.Now;
            Solicitud _oSolicitud = new Solicitud();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(solicitud),
                    Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44334/api/Solicitud", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                     _oSolicitud = JsonConvert.DeserializeObject<Solicitud>(apiResponse);
                }  
            }

            return _oSolicitud;
        }
    }
}


AppConsumer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppConsumer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppConsumer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solicitud" asp-action="Consulta">Consulta Matrícula</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solicitud" asp-action="Index">Matrícula</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AppConsumer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>